#!/usr/bin/env python3
"""Rebuild StreetPass fonts from the pinned Noto Sans SC variable font.
Requires fonttools==4.59.2 and Node.js; uses lv_font_conv@1.5.3.
"""
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = "763146584cf0710223441356b4395e279021b0806c196614377a7a0174ae074a"

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--font-tools", type=Path)
    parser.add_argument('--only-polish', action='store_true', help='Keep the complete 1 bpp fallback unchanged')
    args = parser.parse_args()
    if args.font_tools:
        sys.path.insert(0, str(args.font_tools.resolve()))
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise SystemExit("Noto Sans SC source hash differs; review before regenerating")
    npx = shutil.which("npx.cmd" if os.name == "nt" else "npx")
    if not npx:
        raise SystemExit("Node.js npx is required")
    out = ROOT / "build/font-source"
    out.mkdir(parents=True, exist_ok=True)
    common = ''.join(bytes((lead, trail)).decode('gb2312', errors='ignore')
                     for lead in range(0xB0, 0xD8) for trail in range(0xA1, 0xFF))
    faces = [(16, 500, 1, 'sp_font_16'), (16, 500, 2, 'sp_font_ui_16'),
             (24, 600, 2, 'sp_font_24')]
    for size, weight, bpp, name in faces:
        if args.only_polish and name == 'sp_font_16':
            continue
        static = out / f"NotoSansSC-{weight}.ttf"
        if not static.exists():
            variable = TTFont(args.font)
            fixed = instantiateVariableFont(variable, {"wght": weight}, inplace=True)
            fixed.save(static)
            fixed.close()
        destination = ROOT / f"assets/fonts/{name}.c"
        cmd = [npx, "--yes", "--package", "lv_font_conv@1.5.3", "lv_font_conv",
               "--size", str(size), "--bpp", str(bpp), "--format", "lvgl",
               "--font", str(static), "--no-prefilter", "--no-kerning", "--lv-include", "lvgl.h",
               "--lv-font-name", name, "-o", str(destination)]
        if name == "sp_font_16":
            cmd += ["--range", "0x20-0x7E,0x3000-0x303F,0x4E00-0x9FFF,0xFF00-0xFFEF", "--symbols", "·…—"]
        else:
            cmd += ["--range", "0x20-0x7E,0x3000-0x303F,0xFF00-0xFFEF", "--symbols", common + "·…—"]
        subprocess.run(cmd, check=True)
        text = destination.read_text(encoding="utf-8")
        text = "\n".join(" * Generated by tools/generate_streetpass_fonts.py" if " * Opts:" in line else line for line in text.splitlines()) + "\n"
        destination.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")
        print(f"Generated {destination.name}, weight {weight}", flush=True)

if __name__ == "__main__":
    main()
