#!/usr/bin/env python3
"""Rebuild StreetPass fonts from the pinned Noto Sans SC variable font.
Requires fonttools==4.59.2 and Node.js; uses lv_font_conv@1.5.3.
"""
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = "763146584cf0710223441356b4395e279021b0806c196614377a7a0174ae074a"

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--font-tools", type=Path)
    args = parser.parse_args()
    if args.font_tools:
        sys.path.insert(0, str(args.font_tools.resolve()))
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise SystemExit("Noto Sans SC source hash differs; review before regenerating")
    npx = shutil.which("npx.cmd" if os.name == "nt" else "npx")
    if not npx:
        raise SystemExit("Node.js npx is required")
    out = ROOT / "build/font-source"
    out.mkdir(parents=True, exist_ok=True)
    for size, weight in ((16, 500), (24, 600)):
        static = out / f"NotoSansSC-{weight}.ttf"
        if not static.exists():
            variable = TTFont(args.font)
            fixed = instantiateVariableFont(variable, {"wght": weight}, inplace=True)
            fixed.save(static)
            fixed.close()
        destination = ROOT / f"assets/fonts/sp_font_{size}.c"
        cmd = [npx, "--yes", "--package", "lv_font_conv@1.5.3", "lv_font_conv",
               "--size", str(size), "--bpp", "1" if size==16 else "2", "--format", "lvgl",
               "--font", str(static), "--no-prefilter", "--no-kerning", "--lv-include", "lvgl.h",
               "--lv-font-name", f"sp_font_{size}", "-o", str(destination)]
        if size == 16:
            cmd += ["--range", "0x20-0x7E,0x3000-0x303F,0x4E00-0x9FFF,0xFF00-0xFFEF", "--symbols", "·…—"]
        else:
            cmd += ["--range", "0x20-0x7E", "--symbols", "擦肩名片列表我的扫码编辑打开页设置收到删除联系方式邮箱微信新朋友兴趣简介设备异常"]
        subprocess.run(cmd, check=True)
        text = destination.read_text(encoding="utf-8")
        text = "\n".join(" * Generated by tools/generate_streetpass_fonts.py" if " * Opts:" in line else line for line in text.splitlines()) + "\n"
        destination.write_text(text, encoding="utf-8", newline="\n")
        print(f"Generated {destination.name}, weight {weight}", flush=True)

if __name__ == "__main__":
    main()
